export type SceneMediaKind =
  | "realistic_motion"
  | "technical_diagram"
  | "infographic"
  | "static_visual"
  | "complex_generative";

export type MediaProviderId =
  | "wan2.2"
  | "ltx"
  | "remotion"
  | "static_motion";

export interface MediaRouteInput {
  scene_id: string;
  visual_type:
    | "real_asset"
    | "reference_edit"
    | "generated_image"
    | "technical_diagram"
    | "programmatic_animation";
  requires_natural_motion?: boolean;
  requires_keyframe_interpolation?: boolean;
  requires_deterministic_geometry?: boolean;
}

export interface MediaRoute {
  scene_id: string;
  kind: SceneMediaKind;
  primary: MediaProviderId;
  fallbacks: MediaProviderId[];
  reason: string;
}

export function classifySceneMedia(input: MediaRouteInput): SceneMediaKind {
  if (
    input.visual_type === "technical_diagram" ||
    input.visual_type === "programmatic_animation" ||
    input.requires_deterministic_geometry
  ) {
    return input.visual_type === "technical_diagram"
      ? "technical_diagram"
      : "infographic";
  }

  if (input.requires_keyframe_interpolation) return "complex_generative";
  if (input.requires_natural_motion) return "realistic_motion";
  return "static_visual";
}

export function routeSceneMedia(input: MediaRouteInput): MediaRoute {
  const kind = classifySceneMedia(input);

  switch (kind) {
    case "realistic_motion":
      return {
        scene_id: input.scene_id,
        kind,
        primary: "wan2.2",
        fallbacks: ["static_motion", "remotion"],
        reason:
          "Use image-to-video for natural realistic motion while preserving the approved scene keyframe.",
      };

    case "complex_generative":
      return {
        scene_id: input.scene_id,
        kind,
        primary: "ltx",
        fallbacks: ["wan2.2", "static_motion"],
        reason:
          "Use a multi-keyframe-capable provider first, then degrade to simpler image-to-video or deterministic motion.",
      };

    case "technical_diagram":
    case "infographic":
      return {
        scene_id: input.scene_id,
        kind,
        primary: "remotion",
        fallbacks: ["static_motion"],
        reason:
          "Technical geometry and overlays should stay deterministic instead of being regenerated by a video model.",
      };

    case "static_visual":
      return {
        scene_id: input.scene_id,
        kind,
        primary: "static_motion",
        fallbacks: ["remotion"],
        reason:
          "A controlled pan/zoom is cheaper and more stable when natural generative motion is unnecessary.",
      };
  }
}

export interface ProviderAttempt {
  provider: MediaProviderId;
  attempt: number;
}

export function buildMediaAttemptPlan(
  route: MediaRoute,
  maxAttemptsPerProvider = 3,
): ProviderAttempt[] {
  const providers = [route.primary, ...route.fallbacks];
  return providers.flatMap((provider) =>
    Array.from({length: maxAttemptsPerProvider}, (_, index) => ({
      provider,
      attempt: index + 1,
    })),
  );
}
